trigger:
  branches:
    include:
      - main

stages:
  - stage: BuildAndDeployDEV
    displayName: "Build and Deploy DEV"
    condition: contains(variables['Build.SourceBranch'],'refs/heads/main')
    jobs:
      - job: TerraformInitAndValidate
        displayName: "Terraform Install, Init, and Validate"
        steps:
          - task: TerraformCLI@0
            inputs:
              command: "init"
              backendType: "azurerm"
              backendServiceArm: "Azure subscription 1(1)(f4210fd4-9a8e-484e-b3ab-bf706abb3785)"
              backendAzureRmSubscriptionId: "f4210fd4-9a8e-484e-b3ab-bf706abb3785"
              backendAzureRmResourceGroupName: "tfstate"
              backendAzureRmStorageAccountName: "bestrongtfsate"
              backendAzureRmContainerName: "tfstate"
              backendAzureRmKey: "terraform.tfstate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"

          - task: TerraformCLI@0
            inputs:
              command: "validate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"

          - task: TerraformTaskV4@4
            inputs:
              provider: "azurerm"
              command: "apply"
              environmentServiceNameAzureRM: "Azure subscription 1(1)(f4210fd4-9a8e-484e-b3ab-bf706abb3785)"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"